about/urls.py
from django.urls import path
from about.views import AboutHome


app_name = "about"
urlpatterns = [
    path("", AboutHome.as_view(), name="home")
]

commissions/urls.py
from django.urls import path
from commissions import views


app_name = "commissions"
urlpatterns = [
    path("", views.CommissionsHome.as_view(), name="home"),
]

gallery/urls.py
from django.urls import path
from gallery import views

app_name = "gallery"
urlpatterns = [
    path("", views.GalleryHome.as_view(), name="home")
]

pages/urls.py
from django.urls import path
from pages import views


app_name = "pages"
urlpatterns = [
    path("<slug:slug>/", views.PageView.as_view(), name="page"),
]

viola/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from viola import views

admin.site.site_title = "Viola Bat"
admin.site.site_header = "Viola Bat administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomePageView.as_view(), name="home"),
    path("commissions/", include("commissions.urls", namespace="commissions")),
    path("gallery/", include("gallery.urls", namespace="gallery")),
    path("pages/", include("pages.urls", namespace="pages")),
    path("about/", include("about.urls", namespace="about")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models

# Create your models here.

commissions/models.py
from django.db import models

gallery/models.py
from django.db import models
from taggit.managers import TaggableManager


class GalleryImage(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    order = models.PositiveSmallIntegerField(default=0)
    tags = TaggableManager()
    categories = models.ManyToManyField("GalleryCategory")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["order", "id"]


class GalleryCategory(models.Model):
    name = models.CharField(max_length=50)
    order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name_plural = "gallery categories"

    def __str__(self):
        return self.name

pages/models.py
from django.db import models
from django_quill.fields import QuillField
from django.utils.text import slugify


class Page(models.Model):
    """
    A single web page
    """
    title = models.CharField(max_length=50)
    slug = models.SlugField(null=True, unique=True)
    order = models.PositiveSmallIntegerField(default=0)
    content = QuillField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Option(models.Model):
    """
    An option model to add site-wide variables
    """
    name = models.CharField(max_length=50)
    value = models.TextField()

about/views.py
from django.views import generic
from pages import models as page_models


class AboutHome(generic.TemplateView):
    template_name = "pages/page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = page_models.Page.objects.get(slug="about")
        return context

commissions/views.py
from django.views import generic
from pages import models as page_models


class CommissionsHome(generic.TemplateView):
    template_name = "pages/page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = page_models.Page.objects.get(slug="commissions")
        return context

gallery/views.py
from django.views import generic
from gallery import models
from taggit.models import Tag


class GalleryHome(generic.ListView):
    model = models.GalleryImage
    template_name = "gallery_base.html"
    paginate_by = 24

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag_options"] = list(Tag.objects.values_list("name", flat=True))
        context["selected_tags"] = self.request.GET.getlist("tag")
        context["any_all_tags"] = self.request.GET.get("search") == "all"
        print(self.request.GET.getlist("tag"))
        return context

    def get_queryset(self):
        queryset = models.GalleryImage.objects.all()
        if len(self.request.GET.getlist("tag")) == 0:
            return queryset
        if self.request.GET.get("search") == "all":
            for tag in self.request.GET.getlist("tag"):
                queryset = queryset.filter(tags__name=tag)
        else:
            queryset = queryset.filter(tags__name__in=self.request.GET.getlist("tag")).distinct()
        return queryset

pages/views.py
from django.views import generic
from pages import models


class PageView(generic.DetailView):
    template_name = "pages/page.html"
    model = models.Page

viola/views.py
from django.views import generic


class HomePageView(generic.TemplateView):
    template_name = "home.html"

gallery/templates/gallery_base.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}Gallery | {% endblock %}


{% block content %}
<v-container fill-height>

  <v-card
      color="brown darken-4"
      width="100%"
  >
    <v-card-text class="d-flex align-center">

      <v-autocomplete
          dark
          dense
          chips
          multiple
          outlined
          clearable
          small-chips
          deletable-chips
          label="Search by tags"
          :items="tagOptions"
          v-model="tags"
          class="flex-grow-1"
          :error-messages="tagSearchError"
      ></v-autocomplete>

      <v-switch
          dark
          v-model="anyAllTags"
          :label="anyAllTags ? 'All Tags' : 'Any Tags'"
          color="primary"
          class="d-flex-shrink-1 mb-6 px-3"
      ></v-switch>

      <v-btn
          icon
          x-large
          @click="doSearch"
          color="primary"
          class="flex-shrink-1 mb-6"
      >
        <v-icon>mdi-magnify</v-icon>
      </v-btn>

    </v-card-text>

    <v-card-text class="text-body-1">
      <v-row dense>
        <v-col
            cols="12"
            sm="6"
            md="4"
            lg="2"
            v-for="img in images"
            :key="img.id"
            v-if="images.length"
        >
          <v-hover v-slot="{ hover }">
            <v-img
                :aspect-ratio="1"
                :src="img.image"
                :lazy-src="img.thumb"
                :alt="img.name"
                @click="toggleOverlay(img)"
                :class="`elevation-${hover ? 24 : 0}`"
                class="transition-swing"
            ></v-img>
          </v-hover>
        </v-col>
        {% if not object_list %}
        <v-col cols="12">
          <h3 class="text-h3 text-center white--text">No images</h3>
        </v-col>
        {% endif %}
      </v-row>
    </v-card-text>

    <v-card-actions>
      <v-pagination
          v-model="page"
          :length="pages"
          @input="changePage"
          class="mx-auto"
      ></v-pagination>
    </v-card-actions>

  </v-card>
</v-container>

<v-overlay :value="overlay" @click="overlay = !overlay">

  <v-img
      contain
      :src="activeImage.image"
      v-if="activeImage"
      max-width="100vh"
      max-height="100vh"
  ></v-img>

  <v-hover v-slot="{ hover }">
    <v-footer
        fixed
        padless
        width="100%"
        class="d-flex flex-column justify-center"
        color="transparent"
        :style="{ opacity: hover ? '100%' : '20%' }"
        style="transition: opacity 0.25s ease-in-out"
    >
      <p class="text-body-1">[[ activeImage?.alt ]]</p>
      <v-chip-group column max="0">
        <v-chip
            v-for="tag in activeImage?.tags"
            :key="tag"
            :href="`{% url "gallery:home" %}?tag=${tag}`"
        >
          [[ tag ]]
        </v-chip>
      </v-chip-group>
    </v-footer>
  </v-hover>

</v-overlay>
{% endblock %}


{% block data %}
  page: {{ page_obj.number }},
  pages: {{ page_obj.paginator.num_pages }},
  overlay: false,
  activeImage: null,
  tagOptions: {{ tag_options|safe|default:'[]' }},
  tagSearchError: null,
  tags: {{ selected_tags|safe|default:'[]' }},
  anyAllTags: {{ any_all_tags|yesno:'true,false'|default:'false' }},
  images: [
    {% for img in page_obj %}
      {% thumbnail img.image "100x100" crop="center" as thumb %}
      {
        id: {{ img.id }},
        image: '{{ img.image.url }}',
        thumb: '{{ thumb.url }}',
        alt: '{{ img.name }}',
        tags: [
          {% for tag in img.tags.names %}
            '{{ tag }}',
          {% endfor %}
        ],
      },
      {% endthumbnail %}
    {% endfor %}
  ]
{% endblock %}


{% block methods %}
  changePage(val) {
    let params = ''
    if (val > 1) {
      params = `?page=${val}`
    }
    window.location = '{% url "gallery:home" %}' + params
  },
  toggleOverlay(img) {
    this.activeImage = img
    this.overlay = true
  },
  doSearch() {
    let params = new URLSearchParams()
    for (let tag of this.tags) {
      params.append('tag', tag)
    }
    if (this.anyAllTags) {
      params.set('search', 'all')
    }
    if (params.toString()) {
      window.location = '{% url "gallery:home" %}?' + params.toString()
    } else {
      window.location = '{% url "gallery:home" %}'
    }
  }
{% endblock %}

pages/templates/pages/page.html
{% extends "base.html" %}


{% block title %}{{ object.title }} | {% endblock %}


{% block content %}
  <v-container class="mt-16" id="page-content">
    {{ object.content.html|safe }}
  </v-container>
{% endblock %}


{% block mounted %}
  {# Replace Quill classes with Vuetify classes for consistent styling #}
  const h1s = document.querySelectorAll('#page-content h1')
  for (let h1 of h1s) {
    h1.classList.add('text-h1')
  }

  const h2s = document.querySelectorAll('#page-content h2')
  for (let h2 of h2s) {
    h2.classList.add('text-h2')
  }

  const h3s = document.querySelectorAll('#page-content h3')
  for (let h3 of h3s) {
    h3.classList.add('text-h3')
  }

  const h4s = document.querySelectorAll('#page-content h4')
  for (let h4 of h4s) {
    h4.classList.add('text-h4')
  }

  const h5s = document.querySelectorAll('#page-content h5')
  for (let h5 of h5s) {
    h5.classList.add('text-h5')
  }

  const h6s = document.querySelectorAll('#page-content h6')
  for (let h6 of h6s) {
    h6.classList.add('text-h6')
  }

  const ps = document.querySelectorAll('#page-content p')
  for (let p of ps) {
    p.classList.add('text-body-1')
  }

  const centers = document.querySelectorAll('#page-content .ql-align-center')
  for (let center of centers) {
    center.classList.remove('ql-align-center')
    center.classList.add('text-center')
  }

  const rights = document.querySelectorAll('#page-content .ql-align-right')
  for (let right of rights) {
    right.classList.remove('ql-align-right')
    right.classList.add('text-right')
  }

  const blockquotes = document.querySelectorAll('#page-content blockquote')
  for (let blockquote of blockquotes) {
    blockquote.classList.add('blockquote')
  }

  const colorTexts = document.querySelectorAll('#page-content span')
  for (let colorText of colorTexts) {

    {# Replace Quill text colors with Vuetify text colors #}
    switch (colorText.style.color) {
      case 'rgb(0, 0, 0)':
        colorText.classList.add('black--text');
        break;
      case 'rgb(255, 255, 255)':
        colorText.classList.add('white--text');
        break;
      case 'rgb(187, 187, 187)':
        colorText.classList.add('grey--text', 'text--lighten-1');
        break;
      case 'rgb(136, 136, 136)':
        colorText.classList.add('grey--text');
        break;
      case 'rgb(68, 68, 68)':
        colorText.classList.add('grey--text', 'text--darken-1');
        break;
      case 'rgb(230, 0, 0)':
        colorText.classList.add('red--text');
        break;
      case 'rgb(250, 204, 204)':
        colorText.classList.add('red--text', 'text--lighten-4');
        break;
      case 'rgb(240, 102, 102)':
        colorText.classList.add('red--text', 'text--lighten-2');
        break;
      case 'rgb(161, 0, 0)':
        colorText.classList.add('red--text', 'text--darken-2');
        break;
      case 'rgb(92, 0, 0)':
        colorText.classList.add('red--text', 'text--darken-4');
        break;
      case 'rgb(255, 153, 0)':
        colorText.classList.add('orange--text');
        break;
      case 'rgb(255, 235, 204)':
        colorText.classList.add('orange--text', 'text--lighten-4');
        break;
      case 'rgb(255, 194, 102)':
        colorText.classList.add('orange--text', 'text--lighten-2');
        break;
      case 'rgb(178, 107, 0)':
        colorText.classList.add('orange--text', 'text--darken-2');
        break;
      case 'rgb(102, 61, 0)':
        colorText.classList.add('orange--text', 'text--darken-4');
        break;
      case 'rgb(255, 255, 0)':
        colorText.classList.add('yellow--text');
        break;
      case 'rgb(255, 255, 204)':
        colorText.classList.add('yellow--text', 'text--lighten-4');
        break;
      case 'rgb(255, 255, 102)':
        colorText.classList.add('yellow--text', 'text--lighten-2');
        break;
      case 'rgb(178, 178, 0)':
        colorText.classList.add('yellow--text', 'text--darken-2');
        break;
      case 'rgb(102, 102, 0)':
        colorText.classList.add('yellow--text', 'text--darken-4');
        break;
      case 'rgb(0, 138, 0)':
        colorText.classList.add('green--text');
        break;
      case 'rgb(204, 232, 204)':
        colorText.classList.add('green--text', 'text--lighten-4');
        break;
      case 'rgb(102, 185, 102)':
        colorText.classList.add('green--text', 'text--lighten-2');
        break;
      case 'rgb(0, 97, 0)':
        colorText.classList.add('green--text', 'text--darken-2');
        break;
      case 'rgb(0, 55, 0)':
        colorText.classList.add('green--text', 'text--darken-4');
        break;
      case 'rgb(0, 102, 204)':
        colorText.classList.add('blue--text');
        break;
      case 'rgb(204, 224, 245)':
        colorText.classList.add('blue--text', 'text--lighten-4');
        break;
      case 'rgb(102, 163, 224)':
        colorText.classList.add('blue--text', 'text--lighten-2');
        break;
      case 'rgb(0, 71, 178)':
        colorText.classList.add('blue--text', 'text--darken-2');
        break;
      case 'rgb(0, 41, 102)':
        colorText.classList.add('blue--text', 'text--darken-4');
        break;
      case 'rgb(153, 51, 255)':
        colorText.classList.add('purple--text');
        break;
      case 'rgb(235, 214, 255)':
        colorText.classList.add('purple--text', 'text--lighten-4');
        break;
      case 'rgb(194, 133, 255)':
        colorText.classList.add('purple--text', 'text--lighten-2');
        break;
      case 'rgb(107, 36, 178)':
        colorText.classList.add('purple--text', 'text--darken-2');
        break;
      case 'rgb(61, 20, 102)':
        colorText.classList.add('purple--text', 'text--darken-4');
        break;
      default:
        colorText.classList.add('black--text');
        break;
    }

    {# Replace Quill background colors with Vuetify colors #}
    switch (colorText.style.backgroundColor) {
      case 'rgb(0, 0, 0)':
        colorText.classList.add('black');
        break;
      case 'rgb(255, 255, 255)':
        colorText.classList.add('white');
        break;
      case 'rgb(187, 187, 187)':
        colorText.classList.add('grey', 'lighten-1');
        break;
      case 'rgb(136, 136, 136)':
        colorText.classList.add('grey');
        break;
      case 'rgb(68, 68, 68)':
        colorText.classList.add('grey', 'darken-1');
        break;
      case 'rgb(230, 0, 0)':
        colorText.classList.add('red');
        break;
      case 'rgb(250, 204, 204)':
        colorText.classList.add('red', 'lighten-4');
        break;
      case 'rgb(240, 102, 102)':
        colorText.classList.add('red', 'lighten-2');
        break;
      case 'rgb(161, 0, 0)':
        colorText.classList.add('red', 'darken-2');
        break;
      case 'rgb(92, 0, 0)':
        colorText.classList.add('red', 'darken-4');
        break;
      case 'rgb(255, 153, 0)':
        colorText.classList.add('orange');
        break;
      case 'rgb(255, 235, 204)':
        colorText.classList.add('orange', 'lighten-4');
        break;
      case 'rgb(255, 194, 102)':
        colorText.classList.add('orange', 'lighten-2');
        break;
      case 'rgb(178, 107, 0)':
        colorText.classList.add('orange', 'darken-2');
        break;
      case 'rgb(102, 61, 0)':
        colorText.classList.add('orange', 'darken-4');
        break;
      case 'rgb(255, 255, 0)':
        colorText.classList.add('yellow');
        break;
      case 'rgb(255, 255, 204)':
        colorText.classList.add('yellow', 'lighten-4');
        break;
      case 'rgb(255, 255, 102)':
        colorText.classList.add('yellow', 'lighten-2');
        break;
      case 'rgb(178, 178, 0)':
        colorText.classList.add('yellow', 'darken-2');
        break;
      case 'rgb(102, 102, 0)':
        colorText.classList.add('yellow', 'darken-4');
        break;
      case 'rgb(0, 138, 0)':
        colorText.classList.add('green');
        break;
      case 'rgb(204, 232, 204)':
        colorText.classList.add('green', 'lighten-4');
        break;
      case 'rgb(102, 185, 102)':
        colorText.classList.add('green', 'lighten-2');
        break;
      case 'rgb(0, 97, 0)':
        colorText.classList.add('green', 'darken-2');
        break;
      case 'rgb(0, 55, 0)':
        colorText.classList.add('green', 'darken-4');
        break;
      case 'rgb(0, 102, 204)':
        colorText.classList.add('blue');
        break;
      case 'rgb(204, 224, 245)':
        colorText.classList.add('blue', 'lighten-4');
        break;
      case 'rgb(102, 163, 224)':
        colorText.classList.add('blue', 'lighten-2');
        break;
      case 'rgb(0, 71, 178)':
        colorText.classList.add('blue', 'darken-2');
        break;
      case 'rgb(0, 41, 102)':
        colorText.classList.add('blue', 'darken-4');
        break;
      case 'rgb(153, 51, 255)':
        colorText.classList.add('purple');
        break;
      case 'rgb(235, 214, 255)':
        colorText.classList.add('purple', 'lighten-4');
        break;
      case 'rgb(194, 133, 255)':
        colorText.classList.add('purple', 'lighten-2');
        break;
      case 'rgb(107, 36, 178)':
        colorText.classList.add('purple', 'darken-2');
        break;
      case 'rgb(61, 20, 102)':
        colorText.classList.add('purple', 'darken-4');
        break;
      default:
        colorText.classList.add('black');
        break;
    }
    colorText.style.backgroundColor = null
  }
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=10, minimal-ui">
  <title>{% block title %}{% endblock title %}Viola Bat</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vuetify@2/dist/vuetify.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vue-snotify@3.2.1/styles/material.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/png">
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/png">
  {% block additional_css %}{% endblock %}
  {% block meta %}
    <meta property="og:image" content="{{ site }}{% static "images/gashapon-galaxy-logo.png" %}"/>
    <meta property="og:description" content="Viola Bat's Art"/>
    <meta name="twitter:card" content="summary">
  {% endblock %}
  <meta property="og:site_name" content="Viola Bat">
  <meta property="og:type" content="website">
  <meta name="twitter:site" content="@violabat">
  <meta name="twitter:creator" content="@AtoroDesu">
</head>
<body>
  <v-app id="app" v-cloak>

    <v-main>
      {% block content %}{% endblock %}
      {% if request.path != "/" %}
        <v-btn
            fab
            fixed
            top left
            color="primary"
            href="/"
        >
          <v-icon>mdi-home</v-icon>
        </v-btn>
      {% endif %}
      <vue-snotify></vue-snotify>
    </v-main>

    {% include "footer.html" %}
  </v-app>
{#  {% if debug %}#}
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
{#  {% else %}#}
{#    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.min.js"></script>#}
{#  {% endif %}#}
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2/dist/vuetify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-resource@1/dist/vue-resource.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-snotify@3/vue-snotify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/luxon@2.4.0/build/global/luxon.min.js" integrity="sha256-DIsAGD2EF8Qq2PCH9yzX/yt9FliJfWf+aGcdgR6tKwo=" crossorigin="anonymous"></script>
  {% block additional_vue_scripts %}{% endblock %}

  <script>
    {# Define Python types so any missed vars don't error out the page #}
    const None = null;
    const False = false;
    const True = true;

    {# Define CSRF token for use in POST requests #}
    const csrf_token = Cookies.get('csrftoken');

    {% block vue_use %}{% endblock %}
    const app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#app',
      vuetify: new Vuetify(),
      data: {
        {% block data %}{% endblock %}
      },
      methods: {
        {% block methods %}{% endblock %}
      },
      watch: {
        {% block watch %}{% endblock %}
      },
      computed: {
        {% block computed %}{% endblock %}
      },
      mounted() {
        {% if messages %}
          {% for message in messages %}
            this.$snotify.{{ message.level_tag }}("{{ message|safe }}", "{{ message.tags|title }}", {timeout: 5000}){% if not forloop.last %},{% endif %}
          {% endfor %}
        {% endif %}
        {% block mounted %}{% endblock %}
      },
    });
  </script>
  {% block additional_scripts %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<v-container fill-height>
  <v-row class="text-center">
    <v-col cols="12" class="d-inline-flex flex-column flex-md-row justify-center align-center">
      <div class="mr-md-6">
        <v-avatar size="350">
          <v-img src="{% static 'images/viola.jpg' %}"></v-img>
        </v-avatar>
      </div>
      <div>
        <h1 class="text-h3 text-md-h1 font-weight-bold">Viola Bat's Art</h1>
        <h5 class="text-h5">Freelance Artist who draws dicks</h5>
      </div>
    </v-col>
    <v-col cols="12" class="d-inline-flex flex-column flex-md-row justify-center align-center">
      <v-btn
          depressed
          x-large
          rounded
          dark
          color="#944045"
          class="ma-2"
          min-width="225"
          href="{% url "gallery:home" %}"
      >
        <v-icon left>mdi-view-gallery-outline</v-icon> Gallery
      </v-btn>
      <v-btn
          depressed
          x-large
          rounded
          dark
          color="#944045"
          class="ma-2"
          min-width="225"
          href="{% url "commissions:home" %}"
      >
        <v-icon left>mdi-draw</v-icon> Commissions
      </v-btn>
      <v-btn
          depressed
          x-large
          rounded
          dark
          color="#944045"
          class="ma-2"
          min-width="225"
          href="{% url "about:home" %}"
      >
        <v-icon left>mdi-account-question-outline</v-icon> About Viola Bat
      </v-btn>
      <v-btn
          depressed
          x-large
          rounded
          dark
          color="#944045"
          class="ma-2"
          min-width="225"
          href="https://patreon.com/violabat"
          target="_blank"
      >
        <v-icon left>mdi-patreon</v-icon> Support me!
      </v-btn>
    </v-col>
  </v-row>
</v-container>
{% endblock %}